# Snowflake Configuration
# Copy your actual values here for local testing

[secrets]
SNOWFLAKE_ACCOUNT = "TFLNRNC-FXB95084"
SNOWFLAKE_USERNAME = "SINAVAGHEFI"
SNOWFLAKE_PASSWORD = "SinaOmid2418()"
SNOWFLAKE_DATABASE = "SUHANI_OCPP"
SNOWFLAKE_SCHEMA = "PUBLIC"
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
